version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: mongo:4.0
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    
  neo4jdb:
    image: neo4j:3.5
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  identity.api:
    image: ${REGISTRY:-ecms}/identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile    
    depends_on:
      - sql.data
      
  pages.api:
    image: ${DOCKER_REGISTRY-ecms}/pages.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Pages/Pages.API/Dockerfile
    depends_on:
      - neo4jdb
      - rabbitmq
      - identity.api
      
  webstatus:
    image: ${REGISTRY:-ecms}/webstatus:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebStatus/Dockerfile
    depends_on:
      - neo4jdb
      - rabbitmq
      - pages.api