version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: mongo
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    
  neo4jdb:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/neo4j-neo4jdb/conf:/conf
      - $HOME/neo4j/neo4j-neo4jdb/data:/data
      - $HOME/neo4j/neo4j-neo4jdb/logs:/logs
      - $HOME/neo4j/neo4j-neo4jdb/plugins:/plugins
    environment:
      - NEO4J_AUTH=${ECMS_NEO4J_USERNAME:-neo4j}/${ECMS_NEO4J_PASSWORD:-password}
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  identity.api:
    image: ${REGISTRY:-ecms}/identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile    
    depends_on:
      - sql.data
      
  pages.api:
    image: ${DOCKER_REGISTRY-ecms}/pages.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Pages/Pages.API/Dockerfile
    depends_on:
      - neo4jdb
      - rabbitmq
      - identity.api
      
  webstatus:
    image: ${REGISTRY:-ecms}/webstatus:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebStatus/Dockerfile
    depends_on:
      - neo4jdb
      - rabbitmq
      - pages.api