version: '3.4'

services:
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"    # Important: In a production environment your should remove the external port
  
  nosql.data:
    ports:
      - "27017:27017"  # Important: In a production environment your should remove the external port
  
  neo4jdb:
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/neo4j-neo4jdb/conf:/conf
      - $HOME/neo4j/neo4j-neo4jdb/data:/data
      - $HOME/neo4j/neo4j-neo4jdb/logs:/logs
      - $HOME/neo4j/neo4j-neo4jdb/plugins:/plugins
    environment:
      - NEO4J_AUTH=${ECMS_NEO4J_USERNAME:-neo4j}/${ECMS_NEO4J_PASSWORD:-password}
      
  rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${ECMS_AZURE_IDENTITY_DB:-Server=sql.data;Database=Microsoft.eCMSContainers.Services.IdentityDb;User Id=sa;Password=Pass@word} 
      - PagesApiClient=http://${ECMS_EXTERNAL_DNS_NAME_OR_IP:-localhost}:5010
      - UseCustomizationData=True  
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY:-none}
      - OrchestratorType=${ORCHESTRATOR_TYPE:-none}
    ports:
      - "5105:80"
      
  pages.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P4ssword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/docker-machine-cert.pfx
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5012
      - EventBusConnection=${ECMS_AZURE_SERVICE_BUS:-rabbitmq}
      - Neo4jConnectionString=${ECMS_NEO4J_SERVICE:-http://neo4jdb:7474/db/data}
      - Neo4jUserName=${ECMS_NEO4J_USERNAME:-neo4j}
      - Neo4jPassword=${ECMS_NEO4J_PASSWORD:-password}
      - IdentityUrl=http://identity.api               #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - IdentityUrlExternal=http://${ECMS_EXTERNAL_DNS_NAME_OR_IP:-localhost}:5105
    ports:
      - "5010:80"
      - "5012:443"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https
      
  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecks-UI__HealthChecks__1__Name=Identity HTTP Check
      - HealthChecks-UI__HealthChecks__1__Uri=http://identity.api/hc
      - HealthChecks-UI__HealthChecks__2__Name=Pages HTTP Check
      - HealthChecks-UI__HealthChecks__2__Uri=http://pages.api/hc
    ports:
      - "5107:80"
      
  webspa_angularjs:
    ports:
      - "5104:80"